# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://prashanthvarma.com/
title: Prashanth Varma Manthena
email: me@prashanthvarma.com
author: Mani Prashanth Varma Manthena
description: > # "Mani Prashanth Varma Manthena's Personal Website"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:me@prashanthvarma.com
  - icon: github
    title: github
    url: https://github.com/prashanthvarma
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/prashanthvarma